pool:
  vmImage: ubuntu-latest

steps:
# Starter pipeline
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'nearavenac-devops'
    projectKey: 'nearavenac-devops_pet-clinic'
    projectName: 'pet-clinic'
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'
    spotBugsAnalysis: false
- task: dependency-check-build-task@6
  inputs:
    projectName: 'pet-clinic'
    scanPath: '$(Build.SourcesDirectory)/build/libs'
    format: 'HTML'